#!/bin/bash
set -euo pipefail
# SECURITY-REVIEW: writes a generated Swift file from `git describe` output.
# Input comes from local repo state only; no user-controlled input.

OUT_DIR="${DERIVED_FILE_DIR}"
OUT_FILE="${OUT_DIR}/Version.swift"

VERSION="$(git -C "${SRCROOT}" describe --tags --always --dirty 2>/dev/null || echo unknown)"

mkdir -p "${OUT_DIR}"
NEW_CONTENTS="// Auto-generated by scripts/generate-version.sh. Do not edit.
let APP_VERSION = \"${VERSION}\"
"

# Only rewrite if changed, so unrelated incremental builds stay fast.
if [[ ! -f "${OUT_FILE}" ]] || [[ "$(cat "${OUT_FILE}")" != "${NEW_CONTENTS}" ]]; then
  printf '%s' "${NEW_CONTENTS}" > "${OUT_FILE}"
fi
